find /opt/hypercane -type d -exec chmod 0755 {} \;
find /opt/hypercane -exec chown hypercane:dsa {} \;
chmod 0755 /usr/bin/hc
chown hypercane:dsa /usr/bin/hc
chmod 644 /etc/hypercane.conf
chown hypercane:dsa /etc/hypercane.conf
su -l hypercane -s /bin/bash /opt/hypercane/hypercane-gui/add-hypercane-scripts.sh
/usr/bin/systemctl enable hypercane-celery.service
/usr/bin/systemctl enable hypercane-django.service
